### ISSUE TITLE
话说如果是个人上传公司源码本身就违反规则了吧，删掉貌似也没毛病

### ISSUE THREAD

**Issue by OhYee** [closebilibili/DMCA-takedown#1]
跟着轮子哥的start来围观

**Comment by simon300000** [comment]
感谢轮子哥star

的确没毛病，不过bilibili写的邮件毛病很多→_→

**Comment by Ayase-252** [comment]
就我的理解，这个repo是一个征文比赛？www

**Comment by kj415j45** [comment]
唐突征文太艹wwwwwwwwwwwwwwwwwwwwwwww

**Comment by simon300000** [comment]
对！征文

**Comment by OhYee** [comment]
我以为这是要反讽b站来着，原来是征文
（不过真的没反讽么

**Comment by deemowww** [comment]
跟风踩一脚而已

**Comment by stdcin** [comment]
等待大佬一展文采 😄

**Comment by danny-laa** [comment]
@simon300000 那裡可以找到bilibili写的邮件

**Comment by simon300000** [comment]
@DannyPDWS0041 https://github.com/github/dmca/blob/master/2019/04/2019-04-23-bilibili.md

**Comment by Wittoy** [comment]
有奖励🐴？
