### ISSUE TITLE
请使用官方 DMCA-Takedown 模板

### ISSUE THREAD

**Issue by Flyfish233** [closebilibili/DMCA-takedown#14]
[https://help.github.com/en/articles/dmca-takedown-policy#f-submitting-notices](GitHub-Help)
GitHub 明明有预设模板，套一下就好了，为啥还要自己搞？DMCA-Takedown 不是命题作文...

**Comment by Flyfish233** [comment]
草发错了
[GitHub-Help](https://help.github.com/en/articles/dmca-takedown-policy#f-submitting-notices)

**Comment by simon300000** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/12656264/56747838-440bb100-67b1-11e9-8897-9344a15db8f9.png">
的确有啊，难道你以为这里是真的要给Github发DMCA？
只是B站写的这个DMCA形似命题作文，并且文中许多生草的地方。。。
